const database = [
    { id: 1, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈在開篇提到「古之學者必有師」，當中的「學者」與現代漢語的意思有何不同？", options: ["專指學術上有極高成就的人", "正在學校任教的老師", "求學的人", "博古通今的隱士"], answerLetter: "C", points: 5 },
    { id: 2, subject: "语文", topic: "《师说》", type: "choice", text: "在「師者，所以傳道受業解惑也」中，「所以」的正確語法解釋是什麼？", options: ["連詞，表示因果關係", "代詞，解作「……的原因」", "助詞，用來加強語氣", "結構助詞，表示用來……的／憑藉"], answerLetter: "D", points: 5 },
    { id: 3, subject: "语文", topic: "《师说》", type: "choice", text: "下列哪一項對「其聞道也固先乎吾」中「固」字的解釋最準確？", options: ["堅固", "本來", "頑固", "必定"], answerLetter: "B", points: 5 },
    { id: 4, subject: "语文", topic: "《师说》", type: "choice", text: "關於「傳道受業解惑」，當中的「受」字是什麼用法？", options: ["動詞，接受", "名詞，受難", "通假字，通「授」，傳授", "意動用法，以……為受"], answerLetter: "C", points: 5 },
    { id: 5, subject: "语文", topic: "《师说》", type: "choice", text: "在「吾從而師之」中，「師」字的用法是：", options: ["名詞，老師", "意動用法，以……為師", "使動用法，使……成為老師", "狀語，像老師一樣"], answerLetter: "B", points: 5 },
    { id: 6, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈批評士大夫「愛其子，擇師而教之；於其身也，則恥師焉」，這屬於什麼行為？", options: ["小學而大遺", "聖益聖，愚益愚", "術業有專攻", "不拘於時"], answerLetter: "A", points: 5 },
    { id: 7, subject: "语文", topic: "《师说》", type: "choice", text: "在「小學而大遺」中，「小」和「大」分別指什麼？", options: ["年紀小；年紀大", "學習句讀；領會大道與解惑", "社會地位低；社會地位高", "巫醫樂師；士大夫之族"], answerLetter: "B", points: 5 },
    { id: 8, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈感慨「師道之不傳也久矣」，這裡的「師道」是指：", options: ["老師應有的操守", "從師學習的傳統或風尚", "儒家的仁義道德", "老師的學問深度"], answerLetter: "B", points: 5 },
    { id: 9, subject: "语文", topic: "《师说》", type: "choice", text: "「位卑則足羞，官盛則近諛」反映了士大夫怎樣的擇師心態？", options: ["謙虛謹慎", "趨炎附勢", "重視門第與官位，忽略「道」的存在", "害怕受賄，保持清廉"], answerLetter: "C", points: 5 },
    { id: 10, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈引用「三人行，則必有我師」是為了證明什麼論點？", options: ["人多好辦事", "聖人無常師（擇師不應有固定標準）", "學生一定比不上老師", "孔子是當時最博學的人"], answerLetter: "B", points: 5 },
    { id: 11, subject: "语文", topic: "《师说》", type: "choice", text: "下列哪一組是《師說》中提到的「三重對比」之一？", options: ["韓愈與李蟠", "郯子與孔子", "巫、醫、樂師、百工之人與士大夫之族", "古之學者與今之李蟠"], answerLetter: "C", points: 5 },
    { id: 12, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈嘉許李蟠「能行古道」，這「古道」具體指什麼？", options: ["古代的交通路徑", "古人尊師重道的傳統", "春秋戰國的政治制度", "六經的注釋方法"], answerLetter: "B", points: 5 },
    { id: 13, subject: "语文", topic: "《师说》", type: "choice", text: "「術業有專攻」中的「攻」字意思為何？", options: ["攻擊敵人", "專門研究或學習", "佔領土地", "批評別人的缺點"], answerLetter: "B", points: 5 },
    { id: 14, subject: "语文", topic: "《师说》", type: "choice", text: "為什麼韓愈要提到「郯子之徒，其賢不及孔子」？", options: ["為了貶低郯子的地位", "為了反襯孔子的博學", "為了論證「師不必賢於弟子」", "為了說明孔子找錯了老師"], answerLetter: "C", points: 5 },
    { id: 15, subject: "语文", topic: "《师说》", type: "choice", text: "「句讀之不知，惑之不解，或師焉，或不焉」中，「或」的意思是：", options: ["或者（表示選擇）", "有的（表示部分）", "疑惑（表示不確定）", "假如（表示假設）"], answerLetter: "B", points: 5 },
    { id: 16, subject: "语文", topic: "《师说》", type: "choice", text: "在「其下聖人也亦遠矣」中，「下」字的用法是：", options: ["名詞，下面", "動詞，低於／不及", "狀語，向下地", "使動用法，使……降下"], answerLetter: "B", points: 5 },
    { id: 17, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈認為「弟子不必不如師」，其核心理據是：", options: ["學生通常比老師年輕，更有活力", "老師不一定願意教導學生", "聞道有先後，術業有專攻", "社會風氣已經改變"], answerLetter: "C", points: 5 },
    { id: 18, subject: "语文", topic: "《师说》", type: "choice", text: "「不拘於時」中的「時」是指：", options: ["時間、時鐘", "當時「恥於從師」的敗壞風氣", "特定的歷史朝代", "考試的時限"], answerLetter: "B", points: 5 },
    { id: 19, subject: "语文", topic: "《师说》", type: "choice", text: "下列哪一項最能體現韓愈擇師的標準？", options: ["無貴無賤，無長無少，道之所存，師之所存也", "聖人無常師", "弟子不必不如師", "位卑則足羞，官盛則近諛"], answerLetter: "A", points: 5 },
    { id: 20, subject: "语文", topic: "《师说》", type: "choice", text: "《師說》結尾提到李蟠「六藝經傳皆通習之」，「六藝」指的是：", options: ["禮、樂、射、御、書、數", "詩、書、禮、樂、易、春秋", "文學、修辭、邏輯、數學、天文、地理", "德、智、體、群、美、勞"], answerLetter: "B", points: 5 }
];