const database = [
        { id: 1, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈在開篇提到「古之學者必有師」，當中的「學者」與現代漢語的意思有何不同？", options: ["專指學術上有極高成就的人", "正在學校任教的老師", "求學的人", "博古通今的隱士"], answerLetter: "C", points: 5 },
        { id: 2, subject: "语文", topic: "《师说》", type: "choice", text: "在「師者，所以傳道受業解惑也」中，「所以」的正確語法解釋是什麼？", options: ["連詞，表示因果關係", "代詞，解作「……的原因」", "助詞，用來加強語氣", "結構助詞，表示用來……的／憑藉"], answerLetter: "D", points: 5 },
        { id: 3, subject: "语文", topic: "《师说》", type: "choice", text: "下列哪一項對「其聞道也固先乎吾」中「固」字的解釋最準確？", options: ["堅固", "本來", "頑固", "必定"], answerLetter: "B", points: 5 },
        { id: 4, subject: "语文", topic: "《师说》", type: "choice", text: "關於「傳道受業解惑」，當中的「受」字是什麼用法？", options: ["動詞，接受", "名詞，受難", "通假字，通「授」，傳授", "意動用法，以……為受"], answerLetter: "C", points: 5 },
        { id: 5, subject: "语文", topic: "《师说》", type: "choice", text: "在「吾從而師之」中，「師」字的用法是：", options: ["名詞，老師", "意動用法，以……為師", "使動用法，使……成為老師", "狀語，像老師一樣"], answerLetter: "B", points: 5 },
        { id: 6, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈批評士大夫「愛其子，擇師而教之；於其身也，則恥師焉」，這屬於什麼行為？", options: ["小學而大遺", "聖益聖，愚益愚", "術業有專攻", "不拘於時"], answerLetter: "A", points: 5 },
        { id: 7, subject: "语文", topic: "《师说》", type: "choice", text: "在「小學而大遺」中，「小」和「大」分別指什麼？", options: ["年紀小；年紀大", "學習句讀；領會大道與解惑", "社會地位低；社會地位高", "巫醫樂師；士大夫之族"], answerLetter: "B", points: 5 },
        { id: 8, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈感慨「師道之不傳也久矣」，這裡的「師道」是指：", options: ["老師應有的操守", "從師學習的傳統或風尚", "儒家的仁義道德", "老師的學問深度"], answerLetter: "B", points: 5 },
        { id: 9, subject: "语文", topic: "《师说》", type: "choice", text: "「位卑則足羞，官盛則近諛」反映了士大夫怎樣的擇師心態？", options: ["謙虛謹慎", "趨炎附勢", "重視門第與官位，忽略「道」的存在", "害怕受賄，保持清廉"], answerLetter: "C", points: 5 },
        { id: 10, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈引用「三人行，則必有我師」是為了證明什麼論點？", options: ["人多好辦事", "聖人無常師（擇師不應有固定標準）", "學生一定比不上老師", "孔子是當時最博學的人"], answerLetter: "B", points: 5 },
        { id: 11, subject: "语文", topic: "《师说》", type: "choice", text: "下列哪一組是《師說》中提到的「三重對比」之一？", options: ["韓愈與李蟠", "郯子與孔子", "巫、醫、樂師、百工之人與士大夫之族", "古之學者與今之李蟠"], answerLetter: "C", points: 5 },
        { id: 12, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈嘉許李蟠「能行古道」，這「古道」具體指什麼？", options: ["古代的交通路徑", "古人尊師重道的傳統", "春秋戰國的政治制度", "六經的注釋方法"], answerLetter: "B", points: 5 },
        { id: 13, subject: "语文", topic: "《师说》", type: "choice", text: "「術業有專攻」中的「攻」字意思為何？", options: ["攻擊敵人", "專門研究或學習", "佔領土地", "批評別人的缺點"], answerLetter: "B", points: 5 },
        { id: 14, subject: "语文", topic: "《师说》", type: "choice", text: "為什麼韓愈要提到「郯子之徒，其賢不及孔子」？", options: ["為了貶低郯子的地位", "為了反襯孔子的博學", "為了論證「師不必賢於弟子」", "為了說明孔子找錯了老師"], answerLetter: "C", points: 5 },
        { id: 15, subject: "语文", topic: "《师说》", type: "choice", text: "「句讀之不知，惑之不解，或師焉，或不焉」中，「或」的意思是：", options: ["或者（表示選擇）", "有的（表示部分）", "疑惑（表示不確定）", "假如（表示假設）"], answerLetter: "B", points: 5 },
        { id: 16, subject: "语文", topic: "《师说》", type: "choice", text: "在「其下聖人也亦遠矣」中，「下」字的用法是：", options: ["名詞，下面", "動詞，低於／不及", "狀語，向下地", "使動用法，使……降下"], answerLetter: "B", points: 5 },
        { id: 17, subject: "语文", topic: "《师说》", type: "choice", text: "韓愈認為「弟子不必不如師」，其核心理據是：", options: ["學生通常比老師年輕，更有活力", "老師不一定願意教導學生", "聞道有先後，術業有專攻", "社會風氣已經改變"], answerLetter: "C", points: 5 },
        { id: 18, subject: "语文", topic: "《师说》", type: "choice", text: "「不拘於時」中的「時」是指：", options: ["時間、時鐘", "當時「恥於從師」的敗壞風氣", "特定的歷史朝代", "考試的時限"], answerLetter: "B", points: 5 },
        { id: 19, subject: "语文", topic: "《师说》", type: "choice", text: "下列哪一項最能體現韓愈擇師的標準？", options: ["無貴無賤，無長無少，道之所存，師之所存也", "聖人無常師", "弟子不必不如師", "位卑則足羞，官盛則近諛"], answerLetter: "A", points: 5 },
        { id: 20, subject: "语文", topic: "《师说》", type: "choice", text: "《師說》結尾提到李蟠「六藝經傳皆通習之」，「六藝」指的是：", options: ["禮、樂、射、御、書、數", "詩、書、禮、樂、易、春秋", "文學、修辭、邏輯、數學、天文、地理", "德、智、體、群、美、勞"], answerLetter: "B", points: 5 },
        {"id":21,"subject":"语文","topic":"《师说》","type":"fill","text":"古之学者必有师，学者是什么意思？","points":5,"answerLetter":"求學的人"},
        {"id":22,"subject":"Math","topic":"Basic Math","type":"choice","text":"nmd？","points":5,"options":["x=1","x=2","x=3","x=4"],"answerLetter":"B"},
        {"id":23,"subject":"Chem","topic":"Organic Chemistry","type":"essay","text":"Write down the process of the production of HNIW","points":5,"referenceAnswer":"Grab some CNOH and group them using hands."},
        {"id":25,"subject":"中國語文","topic":"","type":"choice","text":"《論語》的體裁是什麼？","points":5,"options":["議論文","雜記","語錄體","散文"],"answerLetter":"C"},
      {"id":26,"subject":"中國語文","topic":"","type":"choice","text":"承上題，這種體裁有何特點？","points":5,"options":["簡而精","論證嚴密","組織嚴密，結構清晰","文辭綺麗"],"answerLetter":"A"},
      {"id":27,"subject":"中國語文","topic":"","type":"choice","text":"以下選項均是本文特色，何者能反映題1所選的體裁？ <br>(1)多用排比對偶<br> (2)多用反問句<br> (3)以對答建構全文<br> (4)組織沒有章法","points":5,"options":["(1)、(3)","(2)、(3)","(2)、(4)","(2)、(3)、(4)"],"answerLetter":"D"},
      {"id":28,"subject":"中國語文","topic":"","type":"choice","text":"《論語》的作者是誰？ (1)孔子 (2)孔子弟子 (3)孔子親友","points":5,"options":["(1)","(2)","(3)","(1)、(2)"],"answerLetter":"B"},
      {"id":29,"subject":"中國語文","topic":"","type":"choice","text":"「不可以久處約」一句中的「約」字何解？","points":5,"options":["信約","約束","惡劣的環境","貧困的環境"],"answerLetter":"D"},
      {"id":30,"subject":"中國語文","topic":"","type":"choice","text":"「不可以久處約」和「不處也」兩句中的「處」字分別何解？","points":5,"options":["身處；接受","接受；身處","居於；安排","住處；接受"],"answerLetter":"A"},
      {"id":31,"subject":"中國語文","topic":"","type":"choice","text":"「不去也」和「君子去仁」兩句中的「去」字何解？","points":5,"options":["離棄","距離","前往","過去"],"answerLetter":"A"},
      {"id":32,"subject":"中國語文","topic":"","type":"choice","text":"「是人之所惡也」、「惡乎成名」和「不成人之惡」三句中的「惡」字分別何解？","points":5,"options":["討厭；豈；厭惡","厭惡；難道；惡事","討厭；怎麼；惡事","嫌棄；哪；邪惡"],"answerLetter":"C"},
      {"id":33,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項中的粗體字與「為仁由己」中的「為」字意思相近？","points":5,"options":["請事斯語矣。","有殺身以成仁。","克己復禮為仁。","孫以出之。"],"answerLetter":"A"},
      {"id":34,"subject":"中國語文","topic":"","type":"choice","text":"「樊遲御」一句中的「御」字何解？","points":5,"options":["發問","拜訪","迎接","駕車"],"answerLetter":"D"},
      {"id":35,"subject":"中國語文","topic":"","type":"choice","text":"「事父母幾諫」一句中的「幾」字何解？","points":5,"options":["數次","委婉","細心","真誠"],"answerLetter":"B"},
      {"id":36,"subject":"中國語文","topic":"","type":"choice","text":"「過則勿憚改」一句中的「憚」字何解？","points":5,"options":["忌諱","逃避","害怕","擔心"],"answerLetter":"C"},
      {"id":37,"subject":"中國語文","topic":"","type":"choice","text":"「君子義以為質」一句中的「質」字何解？","points":5,"options":["質素","原則","資質","志向"],"answerLetter":"B"},
      {"id":38,"subject":"中國語文","topic":"","type":"choice","text":"「君子求諸己，小人求諸人」一句中的「諸」字何解？","points":5,"options":["各位","之於","許多","諸如"],"answerLetter":"B"},
      {"id":39,"subject":"中國語文","topic":"","type":"choice","text":"「學而時習之，不亦說乎？」一句中的「說」字與哪一個粗體字的意思相近？","points":5,"options":["一則以喜，一則以懼。","子曰……","事父母幾諫……","孟懿子問孝……"],"answerLetter":"A"},
      {"id":40,"subject":"中國語文","topic":"","type":"choice","text":"以下哪些選項屬於倒裝句？ (1)君子病無能焉，不病人之不已知也。(2)生，事之以禮；死，葬之以禮，祭之以禮。(3)君子義以為質，禮以行之，孫以出之，信以成之。君子哉！","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"D"},
      {"id":41,"subject":"中國語文","topic":"","type":"choice","text":"仁者對貧富有何態度？ (1)愛貧嫌富 (2)安貧樂道 (3)堅守仁德","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"C"},
      {"id":42,"subject":"中國語文","topic":"","type":"choice","text":"「不仁者」對錢財有何可能的行為？ (1)為求目的，不擇手段 (2)自我放縱，不加約束 (3)只求利益，不重來源","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"D"},
      {"id":43,"subject":"中國語文","topic":"","type":"choice","text":"試判斷以下哪項有關仁者和知者的描述為正確。 (1)知者也能到達至安仁。 (2)知者行仁時着眼於結果，仁者則着眼於本心。 (3)仁者心安，知者憂懼。","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"A"},
      {"id":44,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項不屬於孔子的金錢觀？","points":5,"options":["不應追求財富和地位。","能以正當方式脫離貧窮。","仁德比金錢更可貴。","追求富貴的利慾乃與生俱來。"],"answerLetter":"A"},
      {"id":45,"subject":"中國語文","topic":"","type":"choice","text":"孔子從哪幾方面闡述行仁的方法？ (1)言行 (2)思想 (3)感官","points":5,"options":["(1) (2)","(1) (3)","(2) (3)","(1) (2) (3)"],"answerLetter":"D"},
      {"id":46,"subject":"中國語文","topic":"","type":"choice","text":"綜合本文，以下哪項是行仁時需具備的決心？ (1)願意付出珍貴生命 (2)無時無刻也要克己 (3)追求完美無瑕成果","points":5,"options":["(1) (2)","(1) (3)","(2) (3)","(1) (2) (3)"],"answerLetter":"A"},
      {"id":47,"subject":"中國語文","topic":"","type":"choice","text":"以下哪個選項正確闡述了「無違」的內涵？","points":5,"options":["無違於父母想法","無違於禮","無違於父母遺願","無違於孔子之教導"],"answerLetter":"B"},
      {"id":48,"subject":"中國語文","topic":"","type":"choice","text":"承上題，試判斷以下哪項符合「無違」的要求。","points":5,"options":["父母生前鬱鬱而終，子女慎終追遠以期補救。","父母提出無理要求，子女順其意思。","父母病重，子女以此為由辭官還鄉照顧他們。","父母犯錯，子女直斥其非以期力挽狂瀾。"],"answerLetter":"C"},
      {"id":49,"subject":"中國語文","topic":"","type":"choice","text":"孔子認為孝道的體現在於什麼？","points":5,"options":["子女的心思","子女所提供的物質","父母之生活品質","父母之意願是否被遵從"],"answerLetter":"A"},
      {"id":50,"subject":"中國語文","topic":"","type":"choice","text":"子女必須做到以下哪種行為？ (1)供養父母生活所需 (2)謹記父母出生年日 (3)擔憂父母逐漸衰老 (4)規勸父母錯誤行為","points":5,"options":["(1) (2)","(2) (4)","(1) (3) (4)","(1) (2) (3) (4)"],"answerLetter":"D"},
      {"id":51,"subject":"中國語文","topic":"","type":"choice","text":"綜合全文，以下哪項最適合用作解釋「孝」的概念？","points":5,"options":["恪守禮儀，緊遵條文。","着重存心，敬養父母。","生養死葬，照顧終老。","不違父意，以德報怨。"],"answerLetter":"B"},
      {"id":52,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項行為屬於「愚孝」之舉？ (1)即使父母違法，依然不加勸阻。 (2)即使父母無理，依然不加抱怨。 (3)即使自己病重，依然關心父母。","points":5,"options":["(1)","(1) (2)","(2) (3)","(1) (2) (3)"],"answerLetter":"A"},
      {"id":53,"subject":"中國語文","topic":"","type":"choice","text":"「一簞食，一瓢飲，在陋巷。人不堪其憂，回也不改其樂。」一句與以下哪句義理相通？ (1)富與貴，是人之所欲也；不以其道得之，不處也。 (2)知者利仁。 (3)無違。 (4)志士仁人，無求生以害仁，有殺身以成仁。","points":5,"options":["(1)","(1) (3)","(2) (4)","(1) (3) (4)"],"answerLetter":"A"},
      {"id":54,"subject":"中國語文","topic":"","type":"choice","text":"子曰：「巧言令色，鮮矣仁！」一句與以下哪句義理最為相通？","points":5,"options":["非禮勿動。","克己復禮為仁……","君子恥其言而過其行。","君子求諸己，小人求諸人。"],"answerLetter":"C"},
      {"id":55,"subject":"中國語文","topic":"","type":"choice","text":"君子以什麼作為行事原則？","points":5,"options":["仁","義","禮","智"],"answerLetter":"B"},
      {"id":56,"subject":"中國語文","topic":"","type":"choice","text":"綜合全文，判斷以下何者符合孔子之思想。 (1)人性本善 (2)君子是仁者 (3)反對人慾","points":5,"options":["(1)","(2)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"B"},
      {"id":57,"subject":"中國語文","topic":"","type":"choice","text":"君子「不憂」和「不病」的對象分別為？","points":5,"options":["自己；自己","他人；自己","自己；他人","他人；他人"],"answerLetter":"C"},
      {"id":58,"subject":"中國語文","topic":"","type":"choice","text":"孔子既說君子「不憂」，又說君子會「病」，為何二者不構成矛盾？","points":5,"options":["孔子說話的語境不同。","孔子教導的學生資質不同。","擔心的對象不同。","擔心的事情不同。"],"answerLetter":"D"},
      {"id":59,"subject":"中國語文","topic":"","type":"choice","text":"以下哪些是君子的特質？ (1)一諾千金 (2)慎於選友 (3)光明磊落","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"D"},
      {"id":60,"subject":"中國語文","topic":"","type":"choice","text":"君子在以下哪些方面與小人有異？ (1)與他人相處的動機 (2)對待父母的態度 (3)對他人之要求","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"B"},
      {"id":61,"subject":"中國語文","topic":"","type":"choice","text":"以下哪一句可以解釋「君子恥其言而過其行」的原因？","points":5,"options":["君子病無能焉，不病人之不已知也。","君子義以為質，禮以行之，孫以出之，信以成之。","君子成人之美，不成人之惡。","君子坦蕩蕩，小人長戚戚。"],"answerLetter":"B"},
      {"id":62,"subject":"中國語文","topic":"","type":"choice","text":"以下哪一句與「君子求諸己，小人求諸人」最為相關？","points":5,"options":["不仁者，不可以久處約，不可以長處樂。","志士仁人，無求生以害仁，有殺身以成仁。","君子病無能焉，不病人之不已知也。","君子去仁，惡乎成名？"],"answerLetter":"C"},
      {"id":63,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項不符合成為君子的條件？ (1)曾犯下彌天大錯 (2)擔憂自己不被賞識 (3)謊話連篇","points":5,"options":["(1) (2)","(1) (3)","(2) (3)","(1) (2) (3)"],"answerLetter":"C"},
      {"id":64,"subject":"中國語文","topic":"","type":"choice","text":"試將下列行為的境界由高至低排列。 (1)利仁 (2)成仁 (3)安仁","points":5,"options":["(3) → (2) → (1)","(2) → (3) → (1)","(3) → (1) → (2)","(1) → (3) → (2)"],"answerLetter":"B"},
      {"id":65,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項是「孝」之要素？","points":5,"options":["養","從","事","敬"],"answerLetter":"D"},
      {"id":66,"subject":"中國語文","topic":"","type":"choice","text":"一心的行為違反了君子哪些特質？ (1)過則勿憚改 (2)無友不如己者 (3)君子不憂不懼 (4)不成人之惡","points":5,"options":["(2)","(1) (4)","(3) (4)","(1) (2) (4)"],"answerLetter":"D"},
      {"id":67,"subject":"中國語文","topic":"","type":"choice","text":"允行的行為體現了君子哪些特質？ (1)內省不疚 (2)君子恥其言而過其行 (3)君子求諸己 (4)過則勿憚改","points":5,"options":["(4)","(1) (3)","(2) (4)","(1) (2) (4)"],"answerLetter":"C"},
      {"id":68,"subject":"中國語文","topic":"","type":"choice","text":"允行的行為違反了君子哪些特質？ (1)主忠信 (2)君子病無能焉…… (3)君子義以為質…… (4)過則勿憚改。","points":5,"options":["(1)","(1) (3)","(3) (4)","(1) (2) (3) (4)"],"answerLetter":"B"},
      {"id":69,"subject":"中國語文","topic":"","type":"choice","text":"根據本文，顏回有何性格特點？ (1)學富五車 (2)尊師重道 (3)謙虛謹慎","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"C"},
      {"id":70,"subject":"中國語文","topic":"","type":"choice","text":"根據本文，孔子有何優點？ (1)對學生因材施教 (2)教學時着重啟發 (3)符合君子的標準","points":5,"options":["(1)、(2)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"A"},
      {"id":71,"subject":"中國語文","topic":"","type":"choice","text":"閱讀以下短文，判斷董永的行為符合以下哪項義理。漢董永，家貧。父死，賣身貸錢而葬。及去僱工，途遇一婦，求為永妻。俱至主家，令織繡三百匹，乃回。一月完成，歸至槐陰會所，遂辭永而去。","points":5,"options":["生，事之以禮；死，葬之以禮，祭之以禮。","不敬，何以別乎？","事父母幾諫","以上皆非"],"answerLetter":"D"},
      {"id":72,"subject":"中國語文","topic":"","type":"choice","text":"閱讀以下短文，判斷郭巨的行為符合以下哪項義理。漢郭巨，家貧。有子三歲，母嘗減食與之。巨謂妻曰：「貧乏不能供母，子又分母之食，盡埋此子？兒可再有，母不可復得。」妻不敢違。巨遂掘坑三尺余，忽見黃金一釜，上云：「天賜孝子郭巨，官不得取，民不得奪。」","points":5,"options":["義以為質，禮以行之。","無違。","父母之年，不可不知也。一則以喜，一則以懼。","以上皆非"],"answerLetter":"D"},
      {"id":73,"subject":"中國語文","topic":"","type":"choice","text":"以下引文運用了哪些修辭手法？君子去仁，惡乎成名？君子無終食之間違仁，造次必於是，顛沛必於是。 (1)設問 (2)對偶 (3)比喻 (4)誇張","points":5,"options":["(1)、(2)","(2)、(3)","(1)、(3)、(4)","(2)、(3)、(4)"],"answerLetter":"B"},
      {"id":74,"subject":"中國語文","topic":"","type":"choice","text":"以下哪一句與「無求生以害仁，有殺身以成仁」運用了完全一樣的修辭手法？","points":5,"options":["生，事之以禮；死，葬之以禮，祭之以禮。","一則以喜，一則以懼。","君子坦蕩蕩，小人長戚戚。","禮以行之，孫以出之，信以成之。"],"answerLetter":"C"},
      {"id":75,"subject":"中國語文","topic":"","type":"choice","text":"孔子以什麼手法帶出子女要尊敬父母的道理？","points":5,"options":["比喻論證","對比論證","引用論證","正反論證"],"answerLetter":"A"},
      {"id":76,"subject":"中國語文","topic":"","type":"choice","text":"「非禮勿視，非禮勿聽，非禮勿言，非禮勿動」一句運用了以下哪項修辭手法？ (1)排比 (2)對比 (3)層遞","points":5,"options":["(1)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"A"},
      {"id":77,"subject":"中國語文","topic":"","type":"choice","text":"「為仁由己，而由人乎哉？」一句所運用的修辭手法如何增強說理效果？ (1)增強語氣 (2)增強諷喻效果 (3)引發讀者思考","points":5,"options":["(1)","(1)、(3)","(2)、(3)","(1)、(2)、(3)"],"answerLetter":"B"},
      {"id":78,"subject":"中國語文","topic":"","type":"choice","text":"孔子言及君子與小人的差異時運用了什麼手法？ (1)對比 (2)對偶 (3)反問","points":5,"options":["(1)","(2)","(1)、(2)","(1)、(2)、(3)"],"answerLetter":"C"},
      {"id":79,"subject":"中國語文","topic":"","type":"choice","text":"以下哪一句沒有運用對比？","points":5,"options":["造次必於是，顛沛必於是。","君子坦蕩蕩，小人長戚戚。","無求生以害仁，有殺身以成仁。","富與貴，是人之所欲也；不以其道得之，不處也。貧與賤，是人之所惡也；不以其道得之，不去也。"],"answerLetter":"A"},
      {"id":80,"subject":"中國語文","topic":"","type":"choice","text":"綜合全文，本文有何特色？","points":5,"options":["言簡意賅，修辭多樣。","文風純樸，不加修飾。","一針見血，辛辣尖銳。","莊諧並重，言之有物。"],"answerLetter":"A"},
      {"id":81,"subject":"中國語文","topic":"","type":"choice","text":"本文的體裁是什麼？","points":5,"options":["問答體","語錄體","議論文","記叙文"],"answerLetter":"A"},
      {"id":82,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項是本文目的？","points":5,"options":["說理","上書","識課","論政"],"answerLetter":"A"},
      {"id":83,"subject":"中國語文","topic":"","type":"choice","text":"《孟子》一書的作者是？","points":5,"options":["孟子","孟子的後人","孟子及其後人","無法考證"],"answerLetter":"C"},
      {"id":84,"subject":"中國語文","topic":"","type":"choice","text":"以下哪項正確描述本文和《孟子》一書的特點？ (1)八篇 (2)每篇分上下卷 (3)每卷分章 (4)本文出自〈告子章句上〉","points":5,"options":["(1)、(2)","(1)、(3)","(1)、(3)、(4)","(2)、(3)、(4)"],"answerLetter":"D"},
      {"id":85,"subject":"中國語文","topic":"","type":"choice","text":"「魚，我所欲也」一句中的「欲」字何解？","points":5,"options":["慾望","想要","肉食","願望"],"answerLetter":"B"},
      {"id":86,"subject":"中國語文","topic":"","type":"choice","text":"「所欲有甚於生者」一句中的「甚」字何解？","points":5,"options":["什麼","怎麼","超過","不及"],"answerLetter":"C"},
      {"id":87,"subject":"中國語文","topic":"","type":"choice","text":"「二者不可得兼」一句中的「得」字何解？","points":5,"options":["應得","得到","得知","得以"],"answerLetter":"B"},
      {"id":88,"subject":"中國語文","topic":"","type":"choice","text":"「二者不可得兼」一句中的「兼」字何解？","points":5,"options":["兼併","同時","兼且","肩負"],"answerLetter":"B"},
      {"id":89,"subject":"中國語文","topic":"","type":"choice","text":"「所識窮乏者得我與」一句中的「得」字何解？","points":5,"options":["感激","得到","得意","成功"],"answerLetter":"A"},
      {"id":90,"subject":"中國語文","topic":"","type":"choice","text":"「所識窮乏者得我與」一句中的「與」字是否通假字？有何意思？","points":5,"options":["通「歟」，語氣詞","通「與」，給予","非通假字，和","非通假字，同"],"answerLetter":"A"},
      {"id":91,"subject":"中國語文","topic":"","type":"choice","text":"「嘑爾而與之」一句中的「嘑」字和「與」字分別何解？","points":5,"options":["呼喝；以及","喝掉；給予","呼喝；給予","喝掉；以及"],"answerLetter":"C"},
      {"id":92,"subject":"中國語文","topic":"","type":"choice","text":"「蹴爾而與之」一句中的「蹴」字何解？","points":5,"options":["呼喝","喝掉","踐踏","踢出"],"answerLetter":"C"},
      {"id":93,"subject":"中國語文","topic":"","type":"choice","text":"「舍魚而取熊掌者也」一句中的「舍」字屬於什麼詞性？有何意思？","points":5,"options":["形容詞；被捨棄的","名詞；舍人","形容詞；舍人的","動詞；捨棄"],"answerLetter":"D"},
      {"id":94,"subject":"中國語文","topic":"","type":"choice","text":"「故患有所不辟也」一句中的「患」字屬於什麼詞性？有何意思？","points":5,"options":["名詞；禍患","動詞；患上","名詞；患者","動詞；擔憂"],"answerLetter":"A"},
      {"id":95,"subject":"中國語文","topic":"","type":"choice","text":"「故患有所不辟也」一句中的「辟」字屬於什麼詞性？有何意思？","points":5,"options":["動詞；辟穀","動詞；避開","動詞；選選","形容詞；辟穀的"],"answerLetter":"B"},
      {"id":96,"subject":"中國語文","topic":"","type":"choice","text":"「萬鍾則不辯禮義而受之」一句中的「辯」字屬於什麼詞性？有何意思？","points":5,"options":["動詞；辯論","動詞；爭論","動詞；辨別","形容詞；容許爭論的"],"answerLetter":"C"},
      {"id":97,"subject":"中國語文","topic":"","type":"choice","text":"「萬鍾與我何加焉」一句中的「萬鍾」何解？","points":5,"options":["千萬的兵器","大量的珍寶","豐厚的獎品","豐厚的俸祿"],"answerLetter":"D"},
      {"id":98,"subject":"中國語文","topic":"","type":"choice","text":"「萬鍾與我何加焉」一句中的「加」字屬於什麼詞性？有何意思？","points":5,"options":["動詞；增益","名詞；加法","形容詞；好的","名詞；利益"],"answerLetter":"D"},
      {"id":99,"subject":"中國語文","topic":"","type":"choice","text":"「鄉為身死而不受」一句中的「鄉」字是否通假字？有何意思？","points":5,"options":["通「向」，從前","通「響」，回想","非通假字，回鄉","非通假字，鄉人"],"answerLetter":"A"}
];
